services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamline_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - streamline
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    container_name: streamline_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - streamline
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    container_name: streamline_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: streamline_api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - streamline

  redis:
    image: redis:7-alpine
    container_name: streamline_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - streamline

  mailhog:
    image: mailhog/mailhog
    container_name: streamline_mailhog
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - streamline

volumes:
  postgres_data:
  redis_data:

networks:
  streamline:
    driver: bridge